### ISSUE TITLE
Wrongly falling into octal system

### ISSUE THREAD

**Issue by brunovalads** [toggledbits/luaxp#8]
For expressions like `"000008"` or  `"76/+08"` or `"902*09"` the `scan_numeric` wrongly assumes it's octal, due the `else radix = 8` condition, so the evaluation throws the "**Invalid digit for radix 8**" error.

**Comment by toggledbits** [comment]
This is correct. An octal constant is defined as starting with a leading 0

**Comment by brunovalads** [comment]
Interesting, I didn't know `0` alone could represent that, I only used `0o` or `0q` in the past.

**Comment by toggledbits** [comment]
I fell back to C. I tend to fall back to underlying languages in stuff like this.
